language: d
sudo: false

os:
  - linux
  - osx

osx_image: xcode9.2

d:
  - dmd-2.078.3
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - ldc-1.7.0
  - ldc-1.6.0
  - ldc-1.5.0
  - ldc-1.4.0
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.1
  - gdc
  - dmd-beta
  - ldc-beta
  - dmd
  - ldc

matrix:
  allow_failures:
    - d: gdc
    - d: dmd-beta
    - d: ldc-beta
    - d: ldc-1.2.0
      os: osx
    - d: ldc-1.3.0
      os: osx
    - d: ldc-1.4.0
      os: osx

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev

